@startuml ClueGame

actor Player
participant Game
participant Board
participant Network
participant Server
participant Client

Player -> Game: Start Game
loop Players Take Turns
    Player -> Game: RollDice()
    Player -> Game: MovePiece()
    alt Accusation Ready?
        Player -> Game: makeAccusation()
        Player -> Game: getGuess()
        Game -> Board: resolveAccusation()
        Board --> Game: accusationResult()
        Game -> Player: getResult()
    else
        Player -> Game: Continue Playing
    end
    Player --> Game: endTurn()
end
Player -> Game: endGame()

Client -> Network: Connect to Server
Network -> Server: Handle Connection
Client -> Network: sendActions
Network -> Server: Process Actions
Server -> Network: Send()
Network --> Client: Receive()

@enduml
